import sys
from enum import Enum

import zserio
from zserio_service_http import HttpClient
import calculator.api as api

class Mode(Enum):
    POWER_OF_TWO = 1
    SQUARE_ROOT = 2

def _printHelp():
    print(
        "Help:",
        " INPUT        Any valid input for the current mode.",
        " p            Sets powerOfTwo(int32) mode.",
        " s            Sets squareRoot(double) mode.",
        " h            Prints this help.",
        " q            Quits the client.",
        "",
        "Note that the letter before the '>' denotes the current mode.",
        sep='\n'
    )

def _powerOfTwo(client, line):
    request = api.I32.fromFields(int(line))
    try:
        response = client.powerOfTwoMethod(request)
    except zserio.ServiceException as e:
        print(e)
    else:
        print(response.getValue())

def _squareRoot(client, line):
    request = api.Double.fromFields(float(line))
    try:
        response = client.squareRootMethod(request)
    except zserio.ServiceException as e:
        print(e)
    else:
        print(response.getValue())

if __name__ == "__main__":
    address = sys.argv[1] if len(sys.argv) > 1 else "localhost:5000"
    (host, port) = address.split(':') if ':' in address else (address, 5000)

    print("Welcome to Zserio Calculator HTTP Client example!")
    print("Waiting for connection (terminate with ^C) ...", end='', flush=True)

    # HttpClient from zserio_service_http library
    httpClient = HttpClient(api.Calculator.Service.SERVICE_FULL_NAME, host, port)
    # Calculator client generated by Zserio, uses httpClient as the service
    client = api.Calculator.Client(httpClient)

    print(" OK!")
    print("Write 'h' + ENTER for help.")

    mode = Mode.POWER_OF_TWO

    while True:
        line = input(('p' if mode == Mode.POWER_OF_TWO else 's') + "> ")
        if not line:
            continue

        if line[0] == 'q':
            print("Quit.")
            exit(0)

        if line[0] == 'h':
            _printHelp()
            continue

        if line[0] == 'p':
            mode = Mode.POWER_OF_TWO
            print("Mode set to powerOfTwo(int32)")
            continue

        if line[0] == 's':
            mode = Mode.SQUARE_ROOT
            print("Mode set to squareRoot(double)")
            continue

        if mode == Mode.POWER_OF_TWO:
            _powerOfTwo(client, line)
        else:
            _squareRoot(client, line)

