name: Windows

on:
  push:
    branches: [ master, '*-ci' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build_windows:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flask
        python -m pip install zserio
        python -m pip install astroid==2.15.0
        python -m pip install pylint==2.16.3
        python -m pip install mypy==0.931
      shell: bash

    - name: Build Zserio Python Service Http
      run: |
        zserio -src examples/calculator calculator.zs -python build/gen
        mypy build/gen examples/calculator src
        PYTHONPATH=build/gen pylint examples src \
              --disable=missing-module-docstring,missing-class-docstring,too-few-public-methods \
              --disable=broad-exception-caught,line-too-long
      shell: bash

    - name: Test Zserio Python Service Http
      run: |
        cd examples/calculator
        python calculator_server.py &
        sleep 10
        echo -e "10\\nq" | python calculator_client.py | grep "p> 100"
        kill $(jobs -p)
      env:
        PYTHONDONTWRITEBYTECODE: 1
        PYTHONPATH: "../../src;../../build/gen"
      shell: bash
